/* automatically generated by rust-bindgen */

pub type XPLMDataRef = *mut ::std::os::raw::c_void;
#[derive(Copy, Clone, Debug)]
#[repr(u32)]
pub enum XPLMDataTypeID {
    xplmType_Unknown = 0,
    xplmType_Int = 1,
    xplmType_Float = 2,
    xplmType_Double = 4,
    xplmType_FloatArray = 8,
    xplmType_IntArray = 16,
    xplmType_Data = 32,
}
pub type XPLMGetDatai_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon:
                                                   *mut ::std::os::raw::c_void)
                              -> ::std::os::raw::c_int>;
pub type XPLMSetDatai_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon:
                                                   *mut ::std::os::raw::c_void,
                                               inValue:
                                                   ::std::os::raw::c_int)>;
pub type XPLMGetDataf_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon:
                                                   *mut ::std::os::raw::c_void)
                              -> ::std::os::raw::c_float>;
pub type XPLMSetDataf_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon:
                                                   *mut ::std::os::raw::c_void,
                                               inValue:
                                                   ::std::os::raw::c_float)>;
pub type XPLMGetDatad_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon:
                                                   *mut ::std::os::raw::c_void)
                              -> ::std::os::raw::c_double>;
pub type XPLMSetDatad_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon:
                                                   *mut ::std::os::raw::c_void,
                                               inValue:
                                                   ::std::os::raw::c_double)>;
pub type XPLMGetDatavi_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon:
                                                   *mut ::std::os::raw::c_void,
                                               outValues:
                                                   *mut ::std::os::raw::c_int,
                                               inOffset:
                                                   ::std::os::raw::c_int,
                                               inMax: ::std::os::raw::c_int)
                              -> ::std::os::raw::c_int>;
pub type XPLMSetDatavi_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon:
                                                   *mut ::std::os::raw::c_void,
                                               inValues:
                                                   *mut ::std::os::raw::c_int,
                                               inOffset:
                                                   ::std::os::raw::c_int,
                                               inCount:
                                                   ::std::os::raw::c_int)>;
pub type XPLMGetDatavf_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon:
                                                   *mut ::std::os::raw::c_void,
                                               outValues:
                                                   *mut ::std::os::raw::c_float,
                                               inOffset:
                                                   ::std::os::raw::c_int,
                                               inMax: ::std::os::raw::c_int)
                              -> ::std::os::raw::c_int>;
pub type XPLMSetDatavf_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon:
                                                   *mut ::std::os::raw::c_void,
                                               inValues:
                                                   *mut ::std::os::raw::c_float,
                                               inOffset:
                                                   ::std::os::raw::c_int,
                                               inCount:
                                                   ::std::os::raw::c_int)>;
pub type XPLMGetDatab_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon:
                                                   *mut ::std::os::raw::c_void,
                                               outValue:
                                                   *mut ::std::os::raw::c_void,
                                               inOffset:
                                                   ::std::os::raw::c_int,
                                               inMaxLength:
                                                   ::std::os::raw::c_int)
                              -> ::std::os::raw::c_int>;
pub type XPLMSetDatab_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon:
                                                   *mut ::std::os::raw::c_void,
                                               inValue:
                                                   *mut ::std::os::raw::c_void,
                                               inOffset:
                                                   ::std::os::raw::c_int,
                                               inLength:
                                                   ::std::os::raw::c_int)>;
pub type XPLMDataChanged_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon:
                                                   *mut ::std::os::raw::c_void)>;
extern "C" {
    pub fn XPLMFindDataRef(inDataRefName: *const ::std::os::raw::c_char)
     -> XPLMDataRef;
    pub fn XPLMCanWriteDataRef(inDataRef: XPLMDataRef)
     -> ::std::os::raw::c_int;
    pub fn XPLMIsDataRefGood(inDataRef: XPLMDataRef) -> ::std::os::raw::c_int;
    pub fn XPLMGetDataRefTypes(inDataRef: XPLMDataRef) -> XPLMDataTypeID;
    pub fn XPLMGetDatai(inDataRef: XPLMDataRef) -> ::std::os::raw::c_int;
    pub fn XPLMSetDatai(inDataRef: XPLMDataRef,
                        inValue: ::std::os::raw::c_int);
    pub fn XPLMGetDataf(inDataRef: XPLMDataRef) -> ::std::os::raw::c_float;
    pub fn XPLMSetDataf(inDataRef: XPLMDataRef,
                        inValue: ::std::os::raw::c_float);
    pub fn XPLMGetDatad(inDataRef: XPLMDataRef) -> ::std::os::raw::c_double;
    pub fn XPLMSetDatad(inDataRef: XPLMDataRef,
                        inValue: ::std::os::raw::c_double);
    pub fn XPLMGetDatavi(inDataRef: XPLMDataRef,
                         outValues: *mut ::std::os::raw::c_int,
                         inOffset: ::std::os::raw::c_int,
                         inMax: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn XPLMSetDatavi(inDataRef: XPLMDataRef,
                         inValues: *mut ::std::os::raw::c_int,
                         inoffset: ::std::os::raw::c_int,
                         inCount: ::std::os::raw::c_int);
    pub fn XPLMGetDatavf(inDataRef: XPLMDataRef,
                         outValues: *mut ::std::os::raw::c_float,
                         inOffset: ::std::os::raw::c_int,
                         inMax: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn XPLMSetDatavf(inDataRef: XPLMDataRef,
                         inValues: *mut ::std::os::raw::c_float,
                         inoffset: ::std::os::raw::c_int,
                         inCount: ::std::os::raw::c_int);
    pub fn XPLMGetDatab(inDataRef: XPLMDataRef,
                        outValue: *mut ::std::os::raw::c_void,
                        inOffset: ::std::os::raw::c_int,
                        inMaxBytes: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn XPLMSetDatab(inDataRef: XPLMDataRef,
                        inValue: *mut ::std::os::raw::c_void,
                        inOffset: ::std::os::raw::c_int,
                        inLength: ::std::os::raw::c_int);
    pub fn XPLMRegisterDataAccessor(inDataName: *const ::std::os::raw::c_char,
                                    inDataType: XPLMDataTypeID,
                                    inIsWritable: ::std::os::raw::c_int,
                                    inReadInt: XPLMGetDatai_f,
                                    inWriteInt: XPLMSetDatai_f,
                                    inReadFloat: XPLMGetDataf_f,
                                    inWriteFloat: XPLMSetDataf_f,
                                    inReadDouble: XPLMGetDatad_f,
                                    inWriteDouble: XPLMSetDatad_f,
                                    inReadIntArray: XPLMGetDatavi_f,
                                    inWriteIntArray: XPLMSetDatavi_f,
                                    inReadFloatArray: XPLMGetDatavf_f,
                                    inWriteFloatArray: XPLMSetDatavf_f,
                                    inReadData: XPLMGetDatab_f,
                                    inWriteData: XPLMSetDatab_f,
                                    inReadRefcon: *mut ::std::os::raw::c_void,
                                    inWriteRefcon:
                                        *mut ::std::os::raw::c_void)
     -> XPLMDataRef;
    pub fn XPLMUnregisterDataAccessor(inDataRef: XPLMDataRef);
    pub fn XPLMShareData(inDataName: *const ::std::os::raw::c_char,
                         inDataType: XPLMDataTypeID,
                         inNotificationFunc: XPLMDataChanged_f,
                         inNotificationRefcon: *mut ::std::os::raw::c_void)
     -> ::std::os::raw::c_int;
    pub fn XPLMUnshareData(inDataName: *const ::std::os::raw::c_char,
                           inDataType: XPLMDataTypeID,
                           inNotificationFunc: XPLMDataChanged_f,
                           inNotificationRefcon: *mut ::std::os::raw::c_void)
     -> ::std::os::raw::c_int;
}
