// Copyright (c) 2015 xplm-sys developers
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT
// license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.

/* automatically generated by rust-bindgen */

pub type XPLMPluginID = ::libc::c_int;
pub type Enum_Unnamed1 = ::libc::c_uint;
pub const xplm_ShiftFlag: ::libc::c_uint = 1;
pub const xplm_OptionAltFlag: ::libc::c_uint = 2;
pub const xplm_ControlFlag: ::libc::c_uint = 4;
pub const xplm_DownFlag: ::libc::c_uint = 8;
pub const xplm_UpFlag: ::libc::c_uint = 16;
pub type XPLMKeyFlags = ::libc::c_int;
