/* automatically generated by rust-bindgen */

pub type XPLMPluginID = ::std::os::raw::c_int;
#[derive(Copy, Clone)]
#[repr(u32)]
pub enum XPLMKeyFlags {
    xplm_ShiftFlag = 1,
    xplm_OptionAltFlag = 2,
    xplm_ControlFlag = 4,
    xplm_DownFlag = 8,
    xplm_UpFlag = 16,
}
