/* automatically generated by rust-bindgen */

pub type XPLMPluginID = ::libc::c_int;
pub type Enum_Unnamed1 = ::libc::c_uint;
pub const xplm_ShiftFlag: ::libc::c_uint = 1;
pub const xplm_OptionAltFlag: ::libc::c_uint = 2;
pub const xplm_ControlFlag: ::libc::c_uint = 4;
pub const xplm_DownFlag: ::libc::c_uint = 8;
pub const xplm_UpFlag: ::libc::c_uint = 16;
pub type XPLMKeyFlags = ::libc::c_int;
