/* automatically generated by rust-bindgen */

#[derive(Copy, Clone)]
#[repr(u32)]
pub enum Enum_Unnamed1 {
    xplm_Menu_NoCheck = 0,
    xplm_Menu_Unchecked = 1,
    xplm_Menu_Checked = 2,
}
pub type XPLMMenuCheck = ::std::os::raw::c_int;
pub type XPLMMenuID = *mut ::std::os::raw::c_void;
pub type XPLMMenuHandler_f =
    ::std::option::Option<unsafe extern "C" fn(inMenuRef:
                                                   *mut ::std::os::raw::c_void,
                                               inItemRef:
                                                   *mut ::std::os::raw::c_void)>;
extern "C" {
    pub fn XPLMFindPluginsMenu() -> XPLMMenuID;
    pub fn XPLMCreateMenu(inName: *const ::std::os::raw::c_char,
                          inParentMenu: XPLMMenuID,
                          inParentItem: ::std::os::raw::c_int,
                          inHandler: XPLMMenuHandler_f,
                          inMenuRef: *mut ::std::os::raw::c_void)
     -> XPLMMenuID;
    pub fn XPLMDestroyMenu(inMenuID: XPLMMenuID);
    pub fn XPLMClearAllMenuItems(inMenuID: XPLMMenuID);
    pub fn XPLMAppendMenuItem(inMenu: XPLMMenuID,
                              inItemName: *const ::std::os::raw::c_char,
                              inItemRef: *mut ::std::os::raw::c_void,
                              inForceEnglish: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn XPLMAppendMenuSeparator(inMenu: XPLMMenuID);
    pub fn XPLMSetMenuItemName(inMenu: XPLMMenuID,
                               inIndex: ::std::os::raw::c_int,
                               inItemName: *const ::std::os::raw::c_char,
                               inForceEnglish: ::std::os::raw::c_int);
    pub fn XPLMCheckMenuItem(inMenu: XPLMMenuID, index: ::std::os::raw::c_int,
                             inCheck: XPLMMenuCheck);
    pub fn XPLMCheckMenuItemState(inMenu: XPLMMenuID,
                                  index: ::std::os::raw::c_int,
                                  outCheck: *mut XPLMMenuCheck);
    pub fn XPLMEnableMenuItem(inMenu: XPLMMenuID,
                              index: ::std::os::raw::c_int,
                              enabled: ::std::os::raw::c_int);
    pub fn XPLMRemoveMenuItem(inMenu: XPLMMenuID,
                              inIndex: ::std::os::raw::c_int);
}
