/* automatically generated by rust-bindgen */

#[derive(Copy, Clone)]
#[repr(u32)]
pub enum Enum_Unnamed1 { xplm_ProbeY = 0, }
pub type XPLMProbeType = ::std::os::raw::c_int;
#[derive(Copy, Clone, Debug)]
#[repr(u32)]
pub enum XPLMProbeResult {
    xplm_ProbeHitTerrain = 0,
    xplm_ProbeError = 1,
    xplm_ProbeMissed = 2,
}
pub type XPLMProbeRef = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Struct_Unnamed3 {
    pub structSize: ::std::os::raw::c_int,
    pub locationX: ::std::os::raw::c_float,
    pub locationY: ::std::os::raw::c_float,
    pub locationZ: ::std::os::raw::c_float,
    pub normalX: ::std::os::raw::c_float,
    pub normalY: ::std::os::raw::c_float,
    pub normalZ: ::std::os::raw::c_float,
    pub velocityX: ::std::os::raw::c_float,
    pub velocityY: ::std::os::raw::c_float,
    pub velocityZ: ::std::os::raw::c_float,
    pub is_wet: ::std::os::raw::c_int,
}
impl ::std::default::Default for Struct_Unnamed3 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type XPLMProbeInfo_t = Struct_Unnamed3;
pub type XPLMObjectRef = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Struct_Unnamed4 {
    pub structSize: ::std::os::raw::c_int,
    pub x: ::std::os::raw::c_float,
    pub y: ::std::os::raw::c_float,
    pub z: ::std::os::raw::c_float,
    pub pitch: ::std::os::raw::c_float,
    pub heading: ::std::os::raw::c_float,
    pub roll: ::std::os::raw::c_float,
}
impl ::std::default::Default for Struct_Unnamed4 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type XPLMDrawInfo_t = Struct_Unnamed4;
pub type XPLMObjectLoaded_f =
    ::std::option::Option<unsafe extern "C" fn(inObject: XPLMObjectRef,
                                               inRefcon:
                                                   *mut ::std::os::raw::c_void)>;
pub type XPLMLibraryEnumerator_f =
    ::std::option::Option<unsafe extern "C" fn(inFilePath:
                                                   *const ::std::os::raw::c_char,
                                               inRef:
                                                   *mut ::std::os::raw::c_void)>;
extern "C" {
    pub fn XPLMCreateProbe(inProbeType: XPLMProbeType) -> XPLMProbeRef;
    pub fn XPLMDestroyProbe(inProbe: XPLMProbeRef);
    pub fn XPLMProbeTerrainXYZ(inProbe: XPLMProbeRef,
                               inX: ::std::os::raw::c_float,
                               inY: ::std::os::raw::c_float,
                               inZ: ::std::os::raw::c_float,
                               outInfo: *mut XPLMProbeInfo_t)
     -> XPLMProbeResult;
    pub fn XPLMLoadObject(inPath: *const ::std::os::raw::c_char)
     -> XPLMObjectRef;
    pub fn XPLMLoadObjectAsync(inPath: *const ::std::os::raw::c_char,
                               inCallback: XPLMObjectLoaded_f,
                               inRefcon: *mut ::std::os::raw::c_void);
    pub fn XPLMDrawObjects(inObject: XPLMObjectRef,
                           inCount: ::std::os::raw::c_int,
                           inLocations: *mut XPLMDrawInfo_t,
                           lighting: ::std::os::raw::c_int,
                           earth_relative: ::std::os::raw::c_int);
    pub fn XPLMUnloadObject(inObject: XPLMObjectRef);
    pub fn XPLMLookupObjects(inPath: *const ::std::os::raw::c_char,
                             inLatitude: ::std::os::raw::c_float,
                             inLongitude: ::std::os::raw::c_float,
                             enumerator: XPLMLibraryEnumerator_f,
                             _ref: *mut ::std::os::raw::c_void)
     -> ::std::os::raw::c_int;
}
