// Copyright (c) 2015 xplm-sys developers
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT
// license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.

/* automatically generated by rust-bindgen */

pub type Enum_Unnamed1 = ::libc::c_uint;
pub const xpMainWindowStyle_MainWindow: ::libc::c_uint = 0;
pub const xpMainWindowStyle_Translucent: ::libc::c_uint = 1;
pub type Enum_Unnamed2 = ::libc::c_uint;
pub const xpProperty_MainWindowType: ::libc::c_uint = 1100;
pub const xpProperty_MainWindowHasCloseBoxes: ::libc::c_uint = 1200;
pub type Enum_Unnamed3 = ::libc::c_uint;
pub const xpMessage_CloseButtonPushed: ::libc::c_uint = 1200;
pub type Enum_Unnamed4 = ::libc::c_uint;
pub const xpSubWindowStyle_SubWindow: ::libc::c_uint = 0;
pub const xpSubWindowStyle_Screen: ::libc::c_uint = 2;
pub const xpSubWindowStyle_ListView: ::libc::c_uint = 3;
pub type Enum_Unnamed5 = ::libc::c_uint;
pub const xpProperty_SubWindowType: ::libc::c_uint = 1200;
pub type Enum_Unnamed6 = ::libc::c_uint;
pub const xpPushButton: ::libc::c_uint = 0;
pub const xpRadioButton: ::libc::c_uint = 1;
pub const xpWindowCloseBox: ::libc::c_uint = 3;
pub const xpLittleDownArrow: ::libc::c_uint = 5;
pub const xpLittleUpArrow: ::libc::c_uint = 6;
pub type Enum_Unnamed7 = ::libc::c_uint;
pub const xpButtonBehaviorPushButton: ::libc::c_uint = 0;
pub const xpButtonBehaviorCheckBox: ::libc::c_uint = 1;
pub const xpButtonBehaviorRadioButton: ::libc::c_uint = 2;
pub type Enum_Unnamed8 = ::libc::c_uint;
pub const xpProperty_ButtonType: ::libc::c_uint = 1300;
pub const xpProperty_ButtonBehavior: ::libc::c_uint = 1301;
pub const xpProperty_ButtonState: ::libc::c_uint = 1302;
pub type Enum_Unnamed9 = ::libc::c_uint;
pub const xpMsg_PushButtonPressed: ::libc::c_uint = 1300;
pub const xpMsg_ButtonStateChanged: ::libc::c_uint = 1301;
pub type Enum_Unnamed10 = ::libc::c_uint;
pub const xpTextEntryField: ::libc::c_uint = 0;
pub const xpTextTransparent: ::libc::c_uint = 3;
pub const xpTextTranslucent: ::libc::c_uint = 4;
pub type Enum_Unnamed11 = ::libc::c_uint;
pub const xpProperty_EditFieldSelStart: ::libc::c_uint = 1400;
pub const xpProperty_EditFieldSelEnd: ::libc::c_uint = 1401;
pub const xpProperty_EditFieldSelDragStart: ::libc::c_uint = 1402;
pub const xpProperty_TextFieldType: ::libc::c_uint = 1403;
pub const xpProperty_PasswordMode: ::libc::c_uint = 1404;
pub const xpProperty_MaxCharacters: ::libc::c_uint = 1405;
pub const xpProperty_ScrollPosition: ::libc::c_uint = 1406;
pub const xpProperty_Font: ::libc::c_uint = 1407;
pub const xpProperty_ActiveEditSide: ::libc::c_uint = 1408;
pub type Enum_Unnamed12 = ::libc::c_uint;
pub const xpMsg_TextFieldChanged: ::libc::c_uint = 1400;
pub type Enum_Unnamed13 = ::libc::c_uint;
pub const xpScrollBarTypeScrollBar: ::libc::c_uint = 0;
pub const xpScrollBarTypeSlider: ::libc::c_uint = 1;
pub type Enum_Unnamed14 = ::libc::c_uint;
pub const xpProperty_ScrollBarSliderPosition: ::libc::c_uint = 1500;
pub const xpProperty_ScrollBarMin: ::libc::c_uint = 1501;
pub const xpProperty_ScrollBarMax: ::libc::c_uint = 1502;
pub const xpProperty_ScrollBarPageAmount: ::libc::c_uint = 1503;
pub const xpProperty_ScrollBarType: ::libc::c_uint = 1504;
pub const xpProperty_ScrollBarSlop: ::libc::c_uint = 1505;
pub type Enum_Unnamed15 = ::libc::c_uint;
pub const xpMsg_ScrollBarSliderPositionChanged: ::libc::c_uint = 1500;
pub type Enum_Unnamed16 = ::libc::c_uint;
pub const xpProperty_CaptionLit: ::libc::c_uint = 1600;
pub type Enum_Unnamed17 = ::libc::c_uint;
pub const xpShip: ::libc::c_uint = 4;
pub const xpILSGlideScope: ::libc::c_uint = 5;
pub const xpMarkerLeft: ::libc::c_uint = 6;
pub const xp_Airport: ::libc::c_uint = 7;
pub const xpNDB: ::libc::c_uint = 8;
pub const xpVOR: ::libc::c_uint = 9;
pub const xpRadioTower: ::libc::c_uint = 10;
pub const xpAircraftCarrier: ::libc::c_uint = 11;
pub const xpFire: ::libc::c_uint = 12;
pub const xpMarkerRight: ::libc::c_uint = 13;
pub const xpCustomObject: ::libc::c_uint = 14;
pub const xpCoolingTower: ::libc::c_uint = 15;
pub const xpSmokeStack: ::libc::c_uint = 16;
pub const xpBuilding: ::libc::c_uint = 17;
pub const xpPowerLine: ::libc::c_uint = 18;
pub const xpVORWithCompassRose: ::libc::c_uint = 19;
pub const xpOilPlatform: ::libc::c_uint = 21;
pub const xpOilPlatformSmall: ::libc::c_uint = 22;
pub const xpWayPoint: ::libc::c_uint = 23;
pub type Enum_Unnamed18 = ::libc::c_uint;
pub const xpProperty_GeneralGraphicsType: ::libc::c_uint = 1700;
pub type Enum_Unnamed19 = ::libc::c_uint;
pub const xpProperty_ProgressPosition: ::libc::c_uint = 1800;
pub const xpProperty_ProgressMin: ::libc::c_uint = 1801;
pub const xpProperty_ProgressMax: ::libc::c_uint = 1802;
