/* automatically generated by rust-bindgen */

#[derive(Copy, Clone)]
#[repr(u32)]
pub enum Enum_Unnamed1 {
    xpWindow_Help = 0,
    xpWindow_MainWindow = 1,
    xpWindow_SubWindow = 2,
    xpWindow_Screen = 4,
    xpWindow_ListView = 5,
}
pub type XPWindowStyle = ::std::os::raw::c_int;
#[derive(Copy, Clone)]
#[repr(u32)]
pub enum Enum_Unnamed2 {
    xpElement_TextField = 6,
    xpElement_CheckBox = 9,
    xpElement_CheckBoxLit = 10,
    xpElement_WindowCloseBox = 14,
    xpElement_WindowCloseBoxPressed = 15,
    xpElement_PushButton = 16,
    xpElement_PushButtonLit = 17,
    xpElement_OilPlatform = 24,
    xpElement_OilPlatformSmall = 25,
    xpElement_Ship = 26,
    xpElement_ILSGlideScope = 27,
    xpElement_MarkerLeft = 28,
    xpElement_Airport = 29,
    xpElement_Waypoint = 30,
    xpElement_NDB = 31,
    xpElement_VOR = 32,
    xpElement_RadioTower = 33,
    xpElement_AircraftCarrier = 34,
    xpElement_Fire = 35,
    xpElement_MarkerRight = 36,
    xpElement_CustomObject = 37,
    xpElement_CoolingTower = 38,
    xpElement_SmokeStack = 39,
    xpElement_Building = 40,
    xpElement_PowerLine = 41,
    xpElement_CopyButtons = 45,
    xpElement_CopyButtonsWithEditingGrid = 46,
    xpElement_EditingGrid = 47,
    xpElement_ScrollBar = 48,
    xpElement_VORWithCompassRose = 49,
    xpElement_Zoomer = 51,
    xpElement_TextFieldMiddle = 52,
    xpElement_LittleDownArrow = 53,
    xpElement_LittleUpArrow = 54,
    xpElement_WindowDragBar = 61,
    xpElement_WindowDragBarSmooth = 62,
}
pub type XPElementStyle = ::std::os::raw::c_int;
#[derive(Copy, Clone)]
#[repr(u32)]
pub enum Enum_Unnamed3 {
    xpTrack_ScrollBar = 0,
    xpTrack_Slider = 1,
    xpTrack_Progress = 2,
}
pub type XPTrackStyle = ::std::os::raw::c_int;
extern "C" {
    pub fn XPDrawWindow(inX1: ::std::os::raw::c_int,
                        inY1: ::std::os::raw::c_int,
                        inX2: ::std::os::raw::c_int,
                        inY2: ::std::os::raw::c_int, inStyle: XPWindowStyle);
    pub fn XPGetWindowDefaultDimensions(inStyle: XPWindowStyle,
                                        outWidth: *mut ::std::os::raw::c_int,
                                        outHeight:
                                            *mut ::std::os::raw::c_int);
    pub fn XPDrawElement(inX1: ::std::os::raw::c_int,
                         inY1: ::std::os::raw::c_int,
                         inX2: ::std::os::raw::c_int,
                         inY2: ::std::os::raw::c_int, inStyle: XPElementStyle,
                         inLit: ::std::os::raw::c_int);
    pub fn XPGetElementDefaultDimensions(inStyle: XPElementStyle,
                                         outWidth: *mut ::std::os::raw::c_int,
                                         outHeight:
                                             *mut ::std::os::raw::c_int,
                                         outCanBeLit:
                                             *mut ::std::os::raw::c_int);
    pub fn XPDrawTrack(inX1: ::std::os::raw::c_int,
                       inY1: ::std::os::raw::c_int,
                       inX2: ::std::os::raw::c_int,
                       inY2: ::std::os::raw::c_int,
                       inMin: ::std::os::raw::c_int,
                       inMax: ::std::os::raw::c_int,
                       inValue: ::std::os::raw::c_int,
                       inTrackStyle: XPTrackStyle,
                       inLit: ::std::os::raw::c_int);
    pub fn XPGetTrackDefaultDimensions(inStyle: XPTrackStyle,
                                       outWidth: *mut ::std::os::raw::c_int,
                                       outCanBeLit:
                                           *mut ::std::os::raw::c_int);
    pub fn XPGetTrackMetrics(inX1: ::std::os::raw::c_int,
                             inY1: ::std::os::raw::c_int,
                             inX2: ::std::os::raw::c_int,
                             inY2: ::std::os::raw::c_int,
                             inMin: ::std::os::raw::c_int,
                             inMax: ::std::os::raw::c_int,
                             inValue: ::std::os::raw::c_int,
                             inTrackStyle: XPTrackStyle,
                             outIsVertical: *mut ::std::os::raw::c_int,
                             outDownBtnSize: *mut ::std::os::raw::c_int,
                             outDownPageSize: *mut ::std::os::raw::c_int,
                             outThumbSize: *mut ::std::os::raw::c_int,
                             outUpPageSize: *mut ::std::os::raw::c_int,
                             outUpBtnSize: *mut ::std::os::raw::c_int);
}
