/* automatically generated by rust-bindgen */

pub type Enum_Unnamed1 = ::libc::c_uint;
pub const xpWindow_Help: ::libc::c_uint = 0;
pub const xpWindow_MainWindow: ::libc::c_uint = 1;
pub const xpWindow_SubWindow: ::libc::c_uint = 2;
pub const xpWindow_Screen: ::libc::c_uint = 4;
pub const xpWindow_ListView: ::libc::c_uint = 5;
pub type XPWindowStyle = ::libc::c_int;
pub type Enum_Unnamed2 = ::libc::c_uint;
pub const xpElement_TextField: ::libc::c_uint = 6;
pub const xpElement_CheckBox: ::libc::c_uint = 9;
pub const xpElement_CheckBoxLit: ::libc::c_uint = 10;
pub const xpElement_WindowCloseBox: ::libc::c_uint = 14;
pub const xpElement_WindowCloseBoxPressed: ::libc::c_uint = 15;
pub const xpElement_PushButton: ::libc::c_uint = 16;
pub const xpElement_PushButtonLit: ::libc::c_uint = 17;
pub const xpElement_OilPlatform: ::libc::c_uint = 24;
pub const xpElement_OilPlatformSmall: ::libc::c_uint = 25;
pub const xpElement_Ship: ::libc::c_uint = 26;
pub const xpElement_ILSGlideScope: ::libc::c_uint = 27;
pub const xpElement_MarkerLeft: ::libc::c_uint = 28;
pub const xpElement_Airport: ::libc::c_uint = 29;
pub const xpElement_Waypoint: ::libc::c_uint = 30;
pub const xpElement_NDB: ::libc::c_uint = 31;
pub const xpElement_VOR: ::libc::c_uint = 32;
pub const xpElement_RadioTower: ::libc::c_uint = 33;
pub const xpElement_AircraftCarrier: ::libc::c_uint = 34;
pub const xpElement_Fire: ::libc::c_uint = 35;
pub const xpElement_MarkerRight: ::libc::c_uint = 36;
pub const xpElement_CustomObject: ::libc::c_uint = 37;
pub const xpElement_CoolingTower: ::libc::c_uint = 38;
pub const xpElement_SmokeStack: ::libc::c_uint = 39;
pub const xpElement_Building: ::libc::c_uint = 40;
pub const xpElement_PowerLine: ::libc::c_uint = 41;
pub const xpElement_CopyButtons: ::libc::c_uint = 45;
pub const xpElement_CopyButtonsWithEditingGrid: ::libc::c_uint = 46;
pub const xpElement_EditingGrid: ::libc::c_uint = 47;
pub const xpElement_ScrollBar: ::libc::c_uint = 48;
pub const xpElement_VORWithCompassRose: ::libc::c_uint = 49;
pub const xpElement_Zoomer: ::libc::c_uint = 51;
pub const xpElement_TextFieldMiddle: ::libc::c_uint = 52;
pub const xpElement_LittleDownArrow: ::libc::c_uint = 53;
pub const xpElement_LittleUpArrow: ::libc::c_uint = 54;
pub const xpElement_WindowDragBar: ::libc::c_uint = 61;
pub const xpElement_WindowDragBarSmooth: ::libc::c_uint = 62;
pub type XPElementStyle = ::libc::c_int;
pub type Enum_Unnamed3 = ::libc::c_uint;
pub const xpTrack_ScrollBar: ::libc::c_uint = 0;
pub const xpTrack_Slider: ::libc::c_uint = 1;
pub const xpTrack_Progress: ::libc::c_uint = 2;
pub type XPTrackStyle = ::libc::c_int;
extern "C" {
    pub fn XPDrawWindow(inX1: ::libc::c_int, inY1: ::libc::c_int,
                        inX2: ::libc::c_int, inY2: ::libc::c_int,
                        inStyle: XPWindowStyle) -> ();
    pub fn XPGetWindowDefaultDimensions(inStyle: XPWindowStyle,
                                        outWidth: *mut ::libc::c_int,
                                        outHeight: *mut ::libc::c_int) -> ();
    pub fn XPDrawElement(inX1: ::libc::c_int, inY1: ::libc::c_int,
                         inX2: ::libc::c_int, inY2: ::libc::c_int,
                         inStyle: XPElementStyle, inLit: ::libc::c_int) -> ();
    pub fn XPGetElementDefaultDimensions(inStyle: XPElementStyle,
                                         outWidth: *mut ::libc::c_int,
                                         outHeight: *mut ::libc::c_int,
                                         outCanBeLit: *mut ::libc::c_int)
     -> ();
    pub fn XPDrawTrack(inX1: ::libc::c_int, inY1: ::libc::c_int,
                       inX2: ::libc::c_int, inY2: ::libc::c_int,
                       inMin: ::libc::c_int, inMax: ::libc::c_int,
                       inValue: ::libc::c_int, inTrackStyle: XPTrackStyle,
                       inLit: ::libc::c_int) -> ();
    pub fn XPGetTrackDefaultDimensions(inStyle: XPTrackStyle,
                                       outWidth: *mut ::libc::c_int,
                                       outCanBeLit: *mut ::libc::c_int) -> ();
    pub fn XPGetTrackMetrics(inX1: ::libc::c_int, inY1: ::libc::c_int,
                             inX2: ::libc::c_int, inY2: ::libc::c_int,
                             inMin: ::libc::c_int, inMax: ::libc::c_int,
                             inValue: ::libc::c_int,
                             inTrackStyle: XPTrackStyle,
                             outIsVertical: *mut ::libc::c_int,
                             outDownBtnSize: *mut ::libc::c_int,
                             outDownPageSize: *mut ::libc::c_int,
                             outThumbSize: *mut ::libc::c_int,
                             outUpPageSize: *mut ::libc::c_int,
                             outUpBtnSize: *mut ::libc::c_int) -> ();
}
