/* automatically generated by rust-bindgen */

use super::widget_defs::{XPWidgetID, XPWidgetClass, XPWidgetFunc_t,
    XPWidgetMessage, XPDispatchMode};

extern "C" {
    pub fn XPCreateWidget(inLeft: ::std::os::raw::c_int,
                          inTop: ::std::os::raw::c_int,
                          inRight: ::std::os::raw::c_int,
                          inBottom: ::std::os::raw::c_int,
                          inVisible: ::std::os::raw::c_int,
                          inDescriptor: *const ::std::os::raw::c_char,
                          inIsRoot: ::std::os::raw::c_int,
                          inContainer: XPWidgetID, inClass: XPWidgetClass)
     -> XPWidgetID;
    pub fn XPCreateCustomWidget(inLeft: ::std::os::raw::c_int,
                                inTop: ::std::os::raw::c_int,
                                inRight: ::std::os::raw::c_int,
                                inBottom: ::std::os::raw::c_int,
                                inVisible: ::std::os::raw::c_int,
                                inDescriptor: *const ::std::os::raw::c_char,
                                inIsRoot: ::std::os::raw::c_int,
                                inContainer: XPWidgetID,
                                inCallback: XPWidgetFunc_t) -> XPWidgetID;
    pub fn XPDestroyWidget(inWidget: XPWidgetID,
                           inDestroyChildren: ::std::os::raw::c_int);
    pub fn XPSendMessageToWidget(inWidget: XPWidgetID,
                                 inMessage: XPWidgetMessage,
                                 inMode: XPDispatchMode, inParam1: isize,
                                 inParam2: isize) -> ::std::os::raw::c_int;
    pub fn XPPlaceWidgetWithin(inSubWidget: XPWidgetID,
                               inContainer: XPWidgetID);
    pub fn XPCountChildWidgets(inWidget: XPWidgetID) -> ::std::os::raw::c_int;
    pub fn XPGetNthChildWidget(inWidget: XPWidgetID,
                               inIndex: ::std::os::raw::c_int) -> XPWidgetID;
    pub fn XPGetParentWidget(inWidget: XPWidgetID) -> XPWidgetID;
    pub fn XPShowWidget(inWidget: XPWidgetID);
    pub fn XPHideWidget(inWidget: XPWidgetID);
    pub fn XPIsWidgetVisible(inWidget: XPWidgetID) -> ::std::os::raw::c_int;
    pub fn XPFindRootWidget(inWidget: XPWidgetID) -> XPWidgetID;
    pub fn XPBringRootWidgetToFront(inWidget: XPWidgetID);
    pub fn XPIsWidgetInFront(inWidget: XPWidgetID) -> ::std::os::raw::c_int;
    pub fn XPGetWidgetGeometry(inWidget: XPWidgetID,
                               outLeft: *mut ::std::os::raw::c_int,
                               outTop: *mut ::std::os::raw::c_int,
                               outRight: *mut ::std::os::raw::c_int,
                               outBottom: *mut ::std::os::raw::c_int);
    pub fn XPSetWidgetGeometry(inWidget: XPWidgetID,
                               inLeft: ::std::os::raw::c_int,
                               inTop: ::std::os::raw::c_int,
                               inRight: ::std::os::raw::c_int,
                               inBottom: ::std::os::raw::c_int);
    pub fn XPGetWidgetForLocation(inContainer: XPWidgetID,
                                  inXOffset: ::std::os::raw::c_int,
                                  inYOffset: ::std::os::raw::c_int,
                                  inRecursive: ::std::os::raw::c_int,
                                  inVisibleOnly: ::std::os::raw::c_int)
     -> XPWidgetID;
    pub fn XPGetWidgetExposedGeometry(inWidgetID: XPWidgetID,
                                      outLeft: *mut ::std::os::raw::c_int,
                                      outTop: *mut ::std::os::raw::c_int,
                                      outRight: *mut ::std::os::raw::c_int,
                                      outBottom: *mut ::std::os::raw::c_int);
    pub fn XPSetWidgetDescriptor(inWidget: XPWidgetID,
                                 inDescriptor: *const ::std::os::raw::c_char);
    pub fn XPGetWidgetDescriptor(inWidget: XPWidgetID,
                                 outDescriptor: *mut ::std::os::raw::c_char,
                                 inMaxDescLength: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn XPSetWidgetProperty(inWidget: XPWidgetID,
                               inProperty: u32,
                               inValue: isize);
    pub fn XPGetWidgetProperty(inWidget: XPWidgetID,
                               inProperty: u32,
                               inExists: *mut ::std::os::raw::c_int)
     -> isize;
    pub fn XPSetKeyboardFocus(inWidget: XPWidgetID) -> XPWidgetID;
    pub fn XPLoseKeyboardFocus(inWidget: XPWidgetID);
    pub fn XPGetWidgetWithFocus() -> XPWidgetID;
    pub fn XPAddWidgetCallback(inWidget: XPWidgetID,
                               inNewCallback: XPWidgetFunc_t);
    pub fn XPGetWidgetClassFunc(inWidgetClass: XPWidgetClass)
     -> XPWidgetFunc_t;
}
