/* automatically generated by rust-bindgen */

use widgets::widget_defs::{XPWidgetID, XPWidgetClass, XPWidgetFunc_t, XPWidgetMessage,
    XPDispatchMode, XPWidgetPropertyID};

extern "C" {
    pub fn XPCreateWidget(inLeft: ::libc::c_int, inTop: ::libc::c_int,
                          inRight: ::libc::c_int, inBottom: ::libc::c_int,
                          inVisible: ::libc::c_int,
                          inDescriptor: *const ::libc::c_char,
                          inIsRoot: ::libc::c_int, inContainer: XPWidgetID,
                          inClass: XPWidgetClass) -> XPWidgetID;
    pub fn XPCreateCustomWidget(inLeft: ::libc::c_int, inTop: ::libc::c_int,
                                inRight: ::libc::c_int,
                                inBottom: ::libc::c_int,
                                inVisible: ::libc::c_int,
                                inDescriptor: *const ::libc::c_char,
                                inIsRoot: ::libc::c_int,
                                inContainer: XPWidgetID,
                                inCallback: XPWidgetFunc_t) -> XPWidgetID;
    pub fn XPDestroyWidget(inWidget: XPWidgetID,
                           inDestroyChildren: ::libc::c_int) -> ();
    pub fn XPSendMessageToWidget(inWidget: XPWidgetID,
                                 inMessage: XPWidgetMessage,
                                 inMode: XPDispatchMode, inParam1: ::libc::intptr_t,
                                 inParam2: ::libc::intptr_t) -> ::libc::c_int;
    pub fn XPPlaceWidgetWithin(inSubWidget: XPWidgetID,
                               inContainer: XPWidgetID) -> ();
    pub fn XPCountChildWidgets(inWidget: XPWidgetID) -> ::libc::c_int;
    pub fn XPGetNthChildWidget(inWidget: XPWidgetID, inIndex: ::libc::c_int)
     -> XPWidgetID;
    pub fn XPGetParentWidget(inWidget: XPWidgetID) -> XPWidgetID;
    pub fn XPShowWidget(inWidget: XPWidgetID) -> ();
    pub fn XPHideWidget(inWidget: XPWidgetID) -> ();
    pub fn XPIsWidgetVisible(inWidget: XPWidgetID) -> ::libc::c_int;
    pub fn XPFindRootWidget(inWidget: XPWidgetID) -> XPWidgetID;
    pub fn XPBringRootWidgetToFront(inWidget: XPWidgetID) -> ();
    pub fn XPIsWidgetInFront(inWidget: XPWidgetID) -> ::libc::c_int;
    pub fn XPGetWidgetGeometry(inWidget: XPWidgetID,
                               outLeft: *mut ::libc::c_int,
                               outTop: *mut ::libc::c_int,
                               outRight: *mut ::libc::c_int,
                               outBottom: *mut ::libc::c_int) -> ();
    pub fn XPSetWidgetGeometry(inWidget: XPWidgetID, inLeft: ::libc::c_int,
                               inTop: ::libc::c_int, inRight: ::libc::c_int,
                               inBottom: ::libc::c_int) -> ();
    pub fn XPGetWidgetForLocation(inContainer: XPWidgetID,
                                  inXOffset: ::libc::c_int,
                                  inYOffset: ::libc::c_int,
                                  inRecursive: ::libc::c_int,
                                  inVisibleOnly: ::libc::c_int) -> XPWidgetID;
    pub fn XPGetWidgetExposedGeometry(inWidgetID: XPWidgetID,
                                      outLeft: *mut ::libc::c_int,
                                      outTop: *mut ::libc::c_int,
                                      outRight: *mut ::libc::c_int,
                                      outBottom: *mut ::libc::c_int) -> ();
    pub fn XPSetWidgetDescriptor(inWidget: XPWidgetID,
                                 inDescriptor: *const ::libc::c_char) -> ();
    pub fn XPGetWidgetDescriptor(inWidget: XPWidgetID,
                                 outDescriptor: *mut ::libc::c_char,
                                 inMaxDescLength: ::libc::c_int)
     -> ::libc::c_int;
    pub fn XPSetWidgetProperty(inWidget: XPWidgetID,
                               inProperty: XPWidgetPropertyID,
                               inValue: ::libc::intptr_t) -> ();
    pub fn XPGetWidgetProperty(inWidget: XPWidgetID,
                               inProperty: XPWidgetPropertyID,
                               inExists: *mut ::libc::c_int) -> ::libc::intptr_t;
    pub fn XPSetKeyboardFocus(inWidget: XPWidgetID) -> XPWidgetID;
    pub fn XPLoseKeyboardFocus(inWidget: XPWidgetID) -> ();
    pub fn XPGetWidgetWithFocus() -> XPWidgetID;
    pub fn XPAddWidgetCallback(inWidget: XPWidgetID,
                               inNewCallback: XPWidgetFunc_t) -> ();
    pub fn XPGetWidgetClassFunc(inWidgetClass: XPWidgetClass)
     -> XPWidgetFunc_t;
}
