// Copyright (c) 2015 xplm-sys developers
// Licensed under the Apache License, Version 2.0
// <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT
// license <LICENSE-MIT or http://opensource.org/licenses/MIT>,
// at your option. All files in the project carrying such
// notice may not be copied, modified, or distributed except
// according to those terms.

/* automatically generated by rust-bindgen */

use widgets::widget_defs::{XPWidgetClass, XPWidgetID, XPWidgetMessage};

#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed1 {
    pub left: ::libc::c_int,
    pub top: ::libc::c_int,
    pub right: ::libc::c_int,
    pub bottom: ::libc::c_int,
    pub visible: ::libc::c_int,
    pub descriptor: *const ::libc::c_char,
    pub isRoot: ::libc::c_int,
    pub containerIndex: ::libc::c_int,
    pub widgetClass: XPWidgetClass,
}
impl ::std::clone::Clone for Struct_Unnamed1 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed1 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type XPWidgetCreate_t = Struct_Unnamed1;
extern "C" {
    pub fn XPUCreateWidgets(inWidgetDefs: *const XPWidgetCreate_t,
                            inCount: ::libc::c_int, inParamParent: XPWidgetID,
                            ioWidgets: *mut XPWidgetID) -> ();
    pub fn XPUMoveWidgetBy(inWidget: XPWidgetID, inDeltaX: ::libc::c_int,
                           inDeltaY: ::libc::c_int) -> ();
    pub fn XPUFixedLayout(inMessage: XPWidgetMessage, inWidget: XPWidgetID,
                          inParam1: ::libc::intptr_t, inParam2: ::libc::intptr_t)
     -> ::libc::c_int;
    pub fn XPUSelectIfNeeded(inMessage: XPWidgetMessage, inWidget: XPWidgetID,
                             inParam1: ::libc::intptr_t, inParam2: ::libc::intptr_t,
                             inEatClick: ::libc::c_int) -> ::libc::c_int;
    pub fn XPUDefocusKeyboard(inMessage: XPWidgetMessage,
                              inWidget: XPWidgetID, inParam1: ::libc::intptr_t,
                              inParam2: ::libc::intptr_t, inEatClick: ::libc::c_int)
     -> ::libc::c_int;
    pub fn XPUDragWidget(inMessage: XPWidgetMessage, inWidget: XPWidgetID,
                         inParam1: ::libc::intptr_t, inParam2: ::libc::intptr_t,
                         inLeft: ::libc::c_int, inTop: ::libc::c_int,
                         inRight: ::libc::c_int, inBottom: ::libc::c_int)
     -> ::libc::c_int;
}
